version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-prod
    image: "${BACKEND_IMAGE}"
    ports:
      - 5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
      args:
        - NODE_ENV=production
        - REACT_APP_SERVICE_URL=${REACT_APP_SERVICE_URL}
    image: "${FRONTEND_IMAGE}"
    ports:
      - 3000
    depends_on:
      - backend
